/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IUSDOracle, IUSDOracleInterface } from "../IUSDOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUSDOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IUSDOracleInterface {
    return new utils.Interface(_abi) as IUSDOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUSDOracle {
    return new Contract(address, _abi, signerOrProvider) as IUSDOracle;
  }
}
