/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IVaultFarm, IVaultFarmInterface } from "../IVaultFarm";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "syncDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "syncLiquidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "syncWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IVaultFarm__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultFarmInterface {
    return new utils.Interface(_abi) as IVaultFarmInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVaultFarm {
    return new Contract(address, _abi, signerOrProvider) as IVaultFarm;
  }
}
