/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  TokenRecipient,
  TokenRecipientInterface,
} from "../TokenRecipient";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "exData",
        type: "bytes",
      },
    ],
    name: "tokensReceived",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TokenRecipient__factory {
  static readonly abi = _abi;
  static createInterface(): TokenRecipientInterface {
    return new utils.Interface(_abi) as TokenRecipientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenRecipient {
    return new Contract(address, _abi, signerOrProvider) as TokenRecipient;
  }
}
