/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IVaultFarmInterface extends utils.Interface {
  contractName: "IVaultFarm";
  functions: {
    "syncDeposit(address,uint256,address)": FunctionFragment;
    "syncLiquidate(address,address)": FunctionFragment;
    "syncWithdraw(address,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "syncDeposit",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "syncLiquidate",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "syncWithdraw",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "syncDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncLiquidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncWithdraw",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IVaultFarm extends BaseContract {
  contractName: "IVaultFarm";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IVaultFarmInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    syncDeposit(
      _user: string,
      _amount: BigNumberish,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    syncLiquidate(
      _user: string,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    syncWithdraw(
      _user: string,
      _amount: BigNumberish,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  syncDeposit(
    _user: string,
    _amount: BigNumberish,
    asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  syncLiquidate(
    _user: string,
    asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  syncWithdraw(
    _user: string,
    _amount: BigNumberish,
    asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    syncDeposit(
      _user: string,
      _amount: BigNumberish,
      asset: string,
      overrides?: CallOverrides
    ): Promise<void>;

    syncLiquidate(
      _user: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<void>;

    syncWithdraw(
      _user: string,
      _amount: BigNumberish,
      asset: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    syncDeposit(
      _user: string,
      _amount: BigNumberish,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    syncLiquidate(
      _user: string,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    syncWithdraw(
      _user: string,
      _amount: BigNumberish,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    syncDeposit(
      _user: string,
      _amount: BigNumberish,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    syncLiquidate(
      _user: string,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    syncWithdraw(
      _user: string,
      _amount: BigNumberish,
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
